{
  "type": "record",
  "name": "Event",
  "namespace": "streamml",
  "fields": [
    {"name": "event_time", "type": {"type": "long", "logicalType": "timestamp-millis"}},
    {"name": "event_type", "type": {"type": "enum", "name": "EventType", "symbols": ["view", "cart", "remove_from_cart", "purchase"]}},
    {"name": "product_id", "type": "long"},
    {"name": "category_id", "type": "long"},
    {"name": "category_code", "type": ["null", "string"], "default": null},
    {"name": "brand", "type": ["null", "string"], "default": null},
    {"name": "price", "type": "double"},
    {"name": "user_id", "type": "long"},
    {"name": "user_session", "type": ["null", "string"], "default": null}
  ]
}
